networks:
  node:
    driver: bridge

services:
  nginx:
    build: ./docker-compose/nginx/
    ports:
      - 8082:80
    links:
      - main
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node

  main:
    build:
      context: .
    ports:
      - 10200:10200
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node
