networks:
  node:
    driver: bridge

services:
  nginx:
    build: ./docker-compose/nginx/
    ports:
      - 8080:80
    links:
      - display
      - main
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node

  display:
    build:
      context: ./display
    ports:
      - 10401:10401
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node

  main:
    build:
      context: ./main
    ports:
      - 10400:10400
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node
