networks:
  node:
    driver: bridge

services:
  nginx:
    build: ./docker-compose/nginx/
    ports:
      - 8083:80
    links:
      - display
      - main
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node

  display:
    build:
      context: ./display
    ports:
      - 10301:10301
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node

  main:
    build:
      context: ./main
    ports:
      - 10300:10300
    volumes:
      - ${WORKDIR}:${WORKDIR}
    networks:
      - node
