name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        working-directory: build-time-integration
        run: |
          npm install

      - name: Lint Display
        working-directory: build-time-integration
        run: |
          npx nx run display:lint
      - name: Lint Main
        working-directory: build-time-integration
        run: |
          npx nx run main:lint
